# Generated by Django 4.0 on 2021-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Img', models.ImageField(upload_to='')),
                ('Department_Name', models.CharField(max_length=200)),
                ('Department_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('Doctor_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=150)),
                ('Specialisation', models.CharField(default='Specialised In', max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Education', models.TextField()),
            ],
        ),
    ]
