# Generated by Django 4.0 on 2021-12-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Department_ID',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Doctor_ID',
        ),
    ]
