# Generated by Django 4.0 on 2021-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_department_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Department',
            field=models.CharField(choices=[('1', 'Dermatology'), ('2', 'Neurology'), ('3', 'Cardiology'), ('4', 'Orthology'), ('5', 'Gynaecology'), ('6', 'Nephrology'), ('7', 'Gastrology'), ('8', 'Urology'), ('9', 'Onchology')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='Specialisation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
