# Generated by Django 4.0 on 2021-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
