# Generated by Django 4.0 on 2021-12-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
