# Generated by Django 4.0 on 2021-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='phone',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
