# Generated by Django 4.0 on 2021-12-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_appointments_phone_alter_appointments_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
