# Generated by Django 4.0 on 2021-12-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_rename_patient_name_appointment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
