# Generated by Django 4.0 on 2021-12-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_remove_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(default='Day', max_length=200),
        ),
    ]
