# Generated by Django 4.0 on 2021-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(default='Sunday', max_length=200),
        ),
    ]
