# Generated by Django 4.0 on 2021-12-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_appointment_department_alter_appointment_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='department',
            new_name='depart',
        ),
    ]
