# Generated by Django 4.0 on 2022-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_rename_department_appointment_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=150)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
