# Generated by Django 4.0 on 2022-01-15 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_appointment_time_alter_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default=datetime.date(2022, 1, 15), max_length=50),
        ),
    ]
