# Generated by Django 4.0 on 2022-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
