# Generated by Django 4.0 on 2022-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
