# Generated by Django 4.0 on 2022-01-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0024_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_address',
            new_name='email',
        ),
    ]
