# Generated by Django 4.0 on 2022-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0025_rename_email_address_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
