# Generated by Django 4.0 on 2022-01-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0026_rename_name_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
    ]
