# Generated by Django 4.0 on 2022-01-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='dateTime',
        ),
    ]
