# Generated by Django 4.0 on 2022-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0032_remove_appointment_datetime_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='', max_length=200),
        ),
    ]
