# Generated by Django 4.0 on 2022-02-04 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0034_attendance_attendancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
