# Generated by Django 4.0 on 2022-02-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0035_attendance_mark_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_Name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='Department',
            field=models.CharField(choices=[('1', 'Dermatology'), ('2', 'Neurology'), ('3', 'Cardiology'), ('4', 'Orthology'), ('5', 'Gynaecology'), ('6', 'Nephrology'), ('7', 'Gastrology'), ('8', 'Urology'), ('9', 'Onchology')], default=' ', max_length=200),
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.member'),
        ),
    ]
