# Generated by Django 4.0 on 2022-02-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0037_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.department'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
