# Generated by Django 4.0 on 2022-02-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0038_alter_member_department_delete_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_Name',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Orthology', 'Orthology'), ('Gynaecology', 'Gynaecology'), ('Nephrology', 'Nephrology'), ('7', 'Gastrology'), ('Urology', 'Urology'), ('Onchology', 'Onchology')], default=' ', max_length=200),
        ),
    ]
